# Generated by Django 4.0.3 on 2022-05-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.URLField(max_length=1000)),
                ('responsible_officials', models.URLField(max_length=1000)),
                ('complaint_info', models.URLField(max_length=1000)),
                ('events_info', models.URLField(max_length=1000)),
                ('region', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
